version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: text-analyzer-tool
    container_name: text-analyzer-tool
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=my-express-app
      - KEYCLOAK_CLIENT_SECRET=my-client-secret
    depends_on:
      - db
      - keycloak

  db:
    image: mysql:8.2.0
    container_name: text-analyzer_db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount init scripts

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak  # Fixed the database URL
      KC_DB_USERNAME: ${DB_USER_NAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: localhost
    command: start-dev
    depends_on:
      - db

volumes:
  db_data:
    driver: local
